// Build-time endpoint: emits /towns.json — town/city reference labels for the
// FDRA maps, generated by scripts/build-towns.mjs from US Census TIGERweb
// places. Consumed by map.js (dots + labels on the danger map and the per-FDRA
// locator maps). Mirrors the map-data.json endpoint so the map layer loads its
// data the same way the boundaries do.
import towns from '../data/towns.json';

export function GET() {
  return new Response(JSON.stringify(towns), {
    headers: { 'Content-Type': 'application/json' },
  });
}
